const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config({ path: require('path').join(__dirname, '../.env') });
const Lesson = require('../models/Lesson');
const Quiz = require('../models/Quiz');
const Challenge = require('../models/Challenge');
const User = require('../models/User');

const c1 = 'WHAT IS CLIMATE CHANGE?\n\nClimate change refers to long-term shifts in global temperatures and weather patterns. Since the 1800s, human activities have been the main driver - primarily burning fossil fuels.\n\nHOW IT WORKS:\nBurning fossil fuels releases greenhouse gases (CO2, methane) into the atmosphere. These gases trap heat from the sun - called the greenhouse effect.\n\nKEY FACTS:\n- Earth has warmed 1.2 degrees C since pre-industrial times\n- CO2 levels are at their highest in 800,000 years\n- Sea levels are rising 3.3mm per year\n- Extreme weather events are becoming more frequent\n\nGREENHOUSE GASES:\n- Carbon Dioxide (CO2): Fossil fuels, deforestation - 76% of emissions\n- Methane (CH4): Agriculture, landfills - 16% of emissions\n- Nitrous Oxide (N2O): Agriculture, fertilizers - 6% of emissions\n\nIMPACTS:\n1. Rising temperatures and more frequent heatwaves\n2. Changing rainfall - more floods and droughts\n3. Melting ice caps and rising sea levels\n4. Ocean acidification harming marine life\n5. Biodiversity loss and ecosystem disruption\n6. Food and water insecurity\n\nTHE PARIS AGREEMENT (2015):\nSigned by 196 countries, aims to limit warming to 1.5 degrees C. Countries submit emission reduction plans called NDCs.\n\nWHAT YOU CAN DO:\n- Reduce energy use at home\n- Choose plant-based foods more often\n- Use public transport, cycle, or walk\n- Support renewable energy\n- Spread awareness in your community';

const c2 = 'BIODIVERSITY AND ECOSYSTEMS\n\nBiodiversity refers to the variety of life on Earth - from genes to species to ecosystems.\n\nTHREE LEVELS:\n1. Genetic diversity - variation within species\n2. Species diversity - variety of different species\n3. Ecosystem diversity - variety of habitats\n\nWHY IT MATTERS:\n- 75% of food crops depend on animal pollination\n- 70% of cancer drugs come from natural sources\n- Forests absorb 2.6 billion tonnes of CO2 per year\n- Nature provides $125-145 trillion in services annually\n\nCURRENT CRISIS:\n- 1 million species face extinction\n- Species disappearing 100-1000x faster than natural rates\n- 75% of land surface significantly altered by humans\n\nFIVE MAIN THREATS:\n1. Land and sea use change (habitat destruction)\n2. Direct exploitation (hunting, fishing, logging)\n3. Climate change\n4. Pollution\n5. Invasive alien species\n\nCONSERVATION STRATEGIES:\n- Protected areas (17% of land, 10% of ocean)\n- Habitat restoration and rewilding\n- Sustainable agriculture and forestry\n- International agreements (CBD, CITES)\n- Community-based conservation';

const c3 = 'DEFORESTATION AND ITS IMPACT\n\nDeforestation is the large-scale removal of forests, primarily for agriculture, logging, and urban expansion.\n\nSCALE:\n- 10 million hectares of forest lost every year\n- That equals 27 football fields every minute\n- Since 1990, we have lost 420 million hectares\n- The Amazon has lost 17% of its forest in 50 years\n\nMAIN CAUSES:\n1. Agriculture (80% of deforestation) - cattle, soy, palm oil\n2. Logging (commercial and illegal)\n3. Infrastructure development\n4. Mining\n5. Urbanization\n\nIMPACTS ON CLIMATE:\n- Forests store 861 billion tonnes of carbon\n- Deforestation releases 10% of global CO2 emissions\n- Trees absorb CO2 through photosynthesis\n- Forests regulate local and regional rainfall\n\nIMPACTS ON BIODIVERSITY:\n- 80% of terrestrial species live in forests\n- Habitat fragmentation isolates populations\n- Keystone species loss causes ecosystem collapse\n\nIMPACTS ON PEOPLE:\n- 1.6 billion people depend on forests for livelihoods\n- Indigenous communities lose homes and culture\n- Increased flooding and landslides\n\nSOLUTIONS:\n- REDD+ (Reducing Emissions from Deforestation)\n- Sustainable Forest Management (FSC certification)\n- Reducing beef and palm oil consumption\n- Reforestation programs\n- Strengthening indigenous land rights';

const c4 = 'CARBON FOOTPRINT BASICS\n\nA carbon footprint is the total greenhouse gases produced by your actions, measured in CO2 equivalent (CO2e).\n\nAVERAGE FOOTPRINTS BY COUNTRY:\n- USA: 16 tonnes CO2e per person per year\n- UK: 8 tonnes\n- India: 2 tonnes\n- Global average: 4 tonnes\n- Target by 2050: Under 2 tonnes\n\nBIGGEST CONTRIBUTORS:\n1. Diet (especially beef and dairy) - up to 30%\n2. Transport (flights, cars) - up to 30%\n3. Home energy (heating, electricity) - up to 25%\n4. Shopping and consumption - up to 15%\n\nFOOD CARBON FOOTPRINT (kg CO2e per kg):\n- Beef: 60 kg\n- Lamb: 24 kg\n- Cheese: 21 kg\n- Pork: 7 kg\n- Chicken: 6 kg\n- Vegetables: under 2 kg\n\nTRANSPORT FOOTPRINT (g CO2e per km):\n- Short-haul flight: 255 g\n- Car (average): 171 g\n- Bus: 89 g\n- Train: 41 g\n- Cycling: 0 g\n\nHOW TO REDUCE:\n1. Eat less meat and dairy (biggest impact)\n2. Avoid flying when possible\n3. Use public transport or cycle\n4. Switch to renewable energy\n5. Buy less, buy second-hand\n6. Reduce food waste';

const c5 = 'OCEAN POLLUTION AND YOU\n\nOur oceans cover 71% of Earth and produce 50% of the oxygen we breathe. Yet they face unprecedented threats.\n\nSCALE OF POLLUTION:\n- 8 million tonnes of plastic enter oceans every year\n- That equals dumping a garbage truck of plastic every minute\n- 700+ marine species threatened by plastic\n- 90% of seabirds have plastic in their stomachs\n- 400+ ocean dead zones worldwide\n\nTYPES OF POLLUTION:\n1. Plastic pollution - bags, bottles, microplastics\n2. Chemical pollution - agricultural runoff, industrial discharge\n3. Oil spills\n4. Noise pollution - disrupts whale communication\n5. Thermal pollution - warm water from power plants\n\nIMPACTS:\n- Coral bleaching: 50% of reefs lost since 1950\n- Entanglement kills 100,000 marine mammals yearly\n- Microplastics found in human blood and lungs\n- Dead zones suffocate all marine life\n\nTHE GREAT PACIFIC GARBAGE PATCH:\n- Twice the size of Texas\n- Contains 80,000 tonnes of plastic\n- Mostly microplastics under 5mm\n\nWHAT YOU CAN DO:\n1. Refuse single-use plastics\n2. Carry reusable bag, bottle, and cup\n3. Participate in beach cleanups\n4. Choose sustainable seafood\n5. Support ocean conservation organizations';

const c6 = 'OCEAN ACIDIFICATION\n\nOcean acidification is called "the other CO2 problem." It is quietly transforming ocean chemistry with devastating consequences.\n\nHOW IT HAPPENS:\n1. We burn fossil fuels, releasing CO2\n2. About 30% of CO2 is absorbed by the ocean\n3. CO2 + water = carbonic acid\n4. More acid = lower pH\n\nTHE NUMBERS:\n- Pre-industrial ocean pH: 8.2\n- Current ocean pH: 8.1\n- This represents a 26% increase in acidity\n- By 2100, pH could reach 7.8 (150% more acidic)\n\nWHO IS AFFECTED:\n1. Coral reefs - dissolve in acidic water\n2. Shellfish - cannot form shells\n3. Fish - disrupted sense of smell and navigation\n4. Plankton - base of marine food web, produces 50% of oxygen\n\nECONOMIC IMPACTS:\n- Shellfish industry worth $1 billion in USA alone\n- Coral reefs support $375 billion in goods and services\n- 500 million people depend on reefs for food and income\n\nSOLUTIONS:\n- Reducing CO2 emissions is the only long-term fix\n- Local actions: reducing runoff, protecting seagrass\n- Marine Protected Areas to reduce other stressors';

const c7 = 'RENEWABLE ENERGY SOURCES\n\nRenewable energy comes from natural sources replenished faster than consumed. Unlike fossil fuels, they produce little to no greenhouse gas emissions.\n\nSOLAR ENERGY:\n- Costs dropped 90% in the last decade\n- Now the cheapest electricity source in history\n- A solar panel pays back its energy cost in 1-4 years\n- Lifespan: 25-30 years\n- Can be installed on rooftops, in deserts, on water\n\nWIND ENERGY:\n- Onshore wind is cheapest electricity in many countries\n- Offshore wind has stronger, more consistent winds\n- A single turbine can power 1,500 homes\n- Lifespan: 20-25 years\n\nHYDROPOWER:\n- Largest renewable source globally (16% of electricity)\n- Reliable and can be turned on/off as needed\n- Large dams can displace communities\n\nGEOTHERMAL:\n- Uses Earth internal heat\n- Available 24/7 regardless of weather\n- Iceland gets 66% of energy from geothermal\n\nENERGY STORAGE:\n- Main challenge for 24/7 renewable energy\n- Lithium-ion batteries most common\n- Green hydrogen is future potential\n\nGLOBAL PROGRESS:\n- Renewables supply 30% of global electricity\n- Target: 100% renewable electricity by 2050\n- Solar and wind now cheaper than coal in most countries';

const c8 = 'WASTE SEGREGATION BASICS\n\nProper waste segregation is the foundation of effective waste management. When sorted correctly, more can be recycled and less ends up in landfill.\n\nTHE FOUR MAIN CATEGORIES:\n\n1. RECYCLABLE (Blue/Yellow bin):\n- Paper and cardboard (clean and dry)\n- Glass bottles and jars\n- Metal cans and tins\n- Hard plastics\nNOT recyclable: greasy boxes, soft plastics, contaminated packaging\n\n2. COMPOSTABLE (Green/Brown bin):\n- Fruit and vegetable scraps\n- Coffee grounds and tea bags\n- Eggshells\n- Garden waste\nNOT compostable: meat, dairy (in home compost)\n\n3. GENERAL WASTE (Black bin):\n- Soft plastics\n- Contaminated packaging\n- Ceramics\n- Nappies and hygiene products\n\n4. HAZARDOUS (Special disposal):\n- Batteries (take to collection points)\n- Electronics (e-waste recycling)\n- Chemicals and paints\n- Medicines (return to pharmacy)\n\nTHE WASTE HIERARCHY:\n1. REFUSE - Do not create waste\n2. REDUCE - Use less\n3. REUSE - Use again\n4. RECYCLE - Process into new materials\n5. ROT - Compost organic waste\n6. DISPOSE - Landfill as last resort\n\nGLOBAL FACTS:\n- 2 billion tonnes of municipal waste generated annually\n- Only 13.5% is recycled\n- Landfills produce methane, a powerful greenhouse gas';

const c9 = 'SUSTAINABLE CITIES\n\nCities cover 3% of land but consume 75% of resources and produce 80% of greenhouse gas emissions. Making them sustainable is critical.\n\nKEY PILLARS:\n\n1. SUSTAINABLE TRANSPORT:\n- Public transport (metro, bus, tram)\n- Cycling infrastructure\n- Electric vehicles\n- Copenhagen: 62% cycle to work\n\n2. GREEN BUILDINGS:\n- Passive design (insulation, natural ventilation)\n- Solar panels and green roofs\n- Smart building management systems\n- Buildings account for 40% of energy use\n\n3. URBAN GREEN SPACES:\n- Parks and gardens\n- Green roofs and walls\n- Urban forests and street trees\n- Singapore: 47% green cover in a dense city\n\n4. WASTE MANAGEMENT:\n- Comprehensive recycling programs\n- Composting facilities\n- San Francisco: 80% diversion from landfill\n\n5. WATER MANAGEMENT:\n- Rainwater harvesting\n- Greywater recycling\n- Permeable surfaces to reduce flooding\n\nCASE STUDIES:\n- Copenhagen: Carbon neutral by 2025\n- Curitiba, Brazil: Pioneer of bus rapid transit\n- Freiburg, Germany: Solar city with car-free zones\n- Amsterdam: 800,000 bicycles for 800,000 people';

const c10 = 'WATER CONSERVATION\n\nOnly 3% of Earth water is fresh, and less than 1% is accessible for human use.\n\nWATER FACTS:\n- 2 billion people lack access to safe drinking water\n- Agriculture uses 70% of global freshwater\n- By 2025, half the world may face water scarcity\n- A dripping tap wastes 3,000 gallons per year\n\nWATER FOOTPRINT OF PRODUCTS:\n- 1 cup of coffee: 140 litres\n- 1 hamburger: 2,400 litres\n- 1 kg of beef: 15,000 litres\n- 1 cotton t-shirt: 2,700 litres\n- 1 kg of vegetables: 300 litres\n\nHOW TO CONSERVE AT HOME:\n1. Fix leaks immediately\n2. Take shorter showers\n3. Turn off tap while brushing teeth\n4. Run full loads in appliances\n5. Collect rainwater for garden\n6. Use drought-resistant plants\n7. Eat less meat (huge water footprint)\n\nCLIMATE AND WATER:\n- Changing rainfall patterns\n- More frequent droughts\n- Glaciers melting (water towers of the world)\n- More intense flooding';

const c11 = 'AIR QUALITY AND HEALTH\n\nAir pollution kills 7 million people per year - more than AIDS, malaria, and tuberculosis combined.\n\nMAIN POLLUTANTS:\n- PM2.5: Fine particles from combustion - most dangerous\n  Penetrates deep into lungs and bloodstream\n- NO2: From vehicles and power plants\n  Causes respiratory inflammation\n- Ozone: From sunlight reacting with pollutants\n  Damages lungs and vegetation\n- Carbon monoxide: From incomplete combustion\n  Reduces oxygen in blood\n- SO2: From coal burning\n  Causes acid rain\n\nHEALTH EFFECTS:\n- Respiratory: Asthma, COPD, lung cancer\n- Cardiovascular: Heart attacks, strokes\n- Neurological: Cognitive impairment in children\n- 99% of world population breathes air exceeding WHO guidelines\n\nMOST VULNERABLE:\n- Children (developing lungs)\n- Elderly\n- People with existing conditions\n- Low-income communities near pollution sources\n\nSOLUTIONS:\n- Transition to electric vehicles\n- Clean cooking fuels\n- Industrial emission controls\n- Urban green spaces (trees filter pollutants)\n- Active transport (cycling, walking)';

const c12 = 'FOOD SYSTEMS AND SUSTAINABILITY\n\nThe food system accounts for 26% of greenhouse gas emissions and uses 50% of habitable land.\n\nFOOD SYSTEM IMPACTS:\n- 70% of freshwater use\n- 80% of deforestation\n- 1/3 of all food produced is wasted\n\nCARBON FOOTPRINT (kg CO2e per kg of food):\n- Beef: 60 kg\n- Lamb: 24 kg\n- Cheese: 21 kg\n- Pork: 7 kg\n- Chicken: 6 kg\n- Rice: 4 kg\n- Vegetables: under 2 kg\n\nFOOD WASTE:\n- 1.3 billion tonnes wasted per year\n- 8% of global greenhouse gas emissions\n- Costs 1 trillion dollars per year\n\nREDUCING FOOD WASTE:\n1. Plan meals and make shopping lists\n2. Store food properly\n3. Understand date labels\n4. Use leftovers creatively\n5. Compost unavoidable waste\n\nSUSTAINABLE DIET:\n1. Eat more plants, less meat\n2. Choose local and seasonal produce\n3. Reduce processed and packaged foods\n4. Grow your own food\n5. Support sustainable farmers\n\nVegan diet uses 75% less land, 54% less water, 73% less emissions than average diet.';

const c13 = 'CLIMATE JUSTICE\n\nClimate justice recognizes that those who contributed least to climate change suffer the most.\n\nTHE INJUSTICE:\n- Richest 10% responsible for 50% of emissions\n- Poorest 50% responsible for only 10% of emissions\n- Yet the poorest are most vulnerable to climate impacts\n\nVULNERABLE GROUPS:\n1. Low-income countries - less resources to adapt\n2. Indigenous peoples - lose lands and livelihoods\n3. Women and girls - more vulnerable to climate disasters\n4. Future generations - inherit consequences of today\n5. Small island states - entire nations face submersion\n\nCASE STUDIES:\n- Bangladesh: 1m sea level rise displaces 17 million people\n- Sub-Saharan Africa: Crop yields could fall 50% by 2050\n- Pakistan: 2022 floods affected 33 million people\n- Pacific Islands: Maldives, Tuvalu face submersion\n\nCLIMATE JUSTICE DEMANDS:\n1. Ambitious emission cuts by wealthy nations\n2. Climate finance for developing nations\n3. Technology transfer\n4. Loss and damage compensation\n5. Inclusion of marginalized voices\n6. Just transition for fossil fuel workers\n\nINTERNATIONAL MECHANISMS:\n- Green Climate Fund: $100 billion per year pledge\n- Loss and Damage Fund (established COP27)\n- Adaptation Fund';

const c14 = 'MARINE ECOSYSTEMS\n\nMarine ecosystems cover 71% of our planet and contain 97% of all water.\n\nMAJOR MARINE ECOSYSTEMS:\n\n1. CORAL REEFS:\n- Cover less than 1% of ocean floor\n- Home to 25% of all marine species\n- Called "rainforests of the sea"\n- Provide food and income for 500 million people\n- Threatened by warming, acidification, and pollution\n\n2. MANGROVES:\n- Coastal forests that grow in saltwater\n- Nurseries for 75% of tropical fish species\n- Store 3-5x more carbon than tropical forests\n- Protect coastlines from storms and erosion\n\n3. SEAGRASS MEADOWS:\n- Nurseries for fish and invertebrates\n- Sequester carbon 35x faster than tropical forests\n- Filter water and stabilize sediments\n\n4. OPEN OCEAN:\n- Largest ecosystem on Earth\n- Home to whales, sharks, tuna, squid\n- Phytoplankton produce 50% of Earth oxygen\n\n5. DEEP SEA:\n- Below 200m depth\n- Least explored ecosystem\n- Home to bioluminescent creatures\n- Threatened by deep-sea mining\n\nFOOD WEBS:\nPhytoplankton -> Zooplankton -> Small fish -> Large fish -> Top predators\n\nKEYSTONE SPECIES:\n- Sea otters control sea urchin populations\n- Sharks regulate fish populations\n- Whales fertilize ocean with nutrient-rich waste';

const c15 = 'SUSTAINABLE FISHING\n\nFish provide 20% of animal protein for 3 billion people. But overfishing is pushing many species to collapse.\n\nTHE OVERFISHING CRISIS:\n- 90% of fish stocks are fully exploited or overfished\n- 33% of commercial fish stocks are overfished\n- Bluefin tuna populations have declined 97%\n- Atlantic cod collapsed in 1992 - still not recovered\n\nPROBLEMS WITH INDUSTRIAL FISHING:\n1. Bycatch - 40% of all catch is unintended species\n2. Bottom trawling - destroys coral and seafloor habitats\n3. Ghost fishing - lost gear continues catching fish\n4. Illegal fishing - worth $23 billion per year\n\nSUSTAINABLE METHODS:\n- Pole-and-line fishing (no bycatch)\n- Handline fishing\n- Trap and pot fishing\n- Responsible aquaculture\n\nMARINE PROTECTED AREAS:\n- Currently protect 8% of the ocean\n- Target: 30% by 2030\n- Allow fish populations to recover\n\nCONSUMER CHOICES:\n- Look for MSC (Marine Stewardship Council) certification\n- Choose lower in the food chain (sardines, mackerel)\n- Avoid endangered species (bluefin tuna, shark fin)\n- Reduce overall fish consumption';

const c16 = 'PLASTIC POLLUTION CRISIS\n\nPlastic was invented in 1907. Since then, 9.2 billion tonnes have been produced. Only 9% has been recycled.\n\nPLASTIC BY THE NUMBERS:\n- 400 million tonnes of plastic produced every year\n- 8 million tonnes enter the ocean annually\n- 5 trillion pieces of plastic in the ocean\n- Plastic takes 400-1000 years to decompose\n- Humans consume about 5g of microplastics per week\n\nTYPES OF PLASTIC POLLUTION:\n1. Macroplastics - bottles, bags, packaging, fishing gear\n2. Microplastics (under 5mm) - from degraded plastics, synthetic fibres\n3. Nanoplastics - can enter cells and cross blood-brain barrier\n\nHEALTH IMPACTS:\n- Endocrine disruption (BPA, phthalates)\n- Found in human blood, lungs, placentas, breast milk\n- Potential carcinogens\n\nTHE SOLUTION HIERARCHY:\n1. REFUSE - Do not accept single-use plastics\n2. REDUCE - Buy less packaged products\n3. REUSE - Use durable alternatives\n4. RECYCLE - Only as a last resort\n\nSINGLE-USE ALTERNATIVES:\n- Plastic bags -> Reusable cloth bags\n- Plastic bottles -> Stainless steel bottle\n- Plastic straws -> Metal or bamboo straws\n- Plastic wrap -> Beeswax wraps\n- Plastic cutlery -> Bamboo or metal cutlery';

const c17 = 'GREEN TECHNOLOGY AND INNOVATION\n\nGreen technology (cleantech) uses renewable materials and energy, reduces emissions, and has minimal environmental impact.\n\nKEY TECHNOLOGIES:\n\n1. ENERGY STORAGE:\n- Lithium-ion batteries (EVs, grid storage)\n- Solid-state batteries (next generation)\n- Green hydrogen (seasonal storage)\n\n2. ELECTRIC VEHICLES:\n- Zero tailpipe emissions\n- 3x more efficient than combustion engines\n- Battery costs dropped 97% since 1991\n- 10 million EVs sold in 2022\n\n3. CARBON CAPTURE (CCS):\n- Captures CO2 from industrial processes\n- Direct Air Capture removes CO2 from atmosphere\n- Currently expensive but costs falling\n\n4. GREEN HYDROGEN:\n- Produced by electrolysis using renewable energy\n- Zero emissions fuel for industry and transport\n- Key for decarbonizing steel, cement, shipping\n\n5. VERTICAL FARMING:\n- Grows food in stacked layers indoors\n- Uses 95% less water than conventional farming\n- No pesticides needed\n- Year-round production\n\n6. SMART BUILDINGS:\n- AI-optimized heating and cooling\n- Automated lighting\n- Can reduce building energy use by 30%\n\nEMERGING TECHNOLOGIES:\n- Lab-grown meat (90% less land, 80% less water)\n- Perovskite solar cells (cheaper, more efficient)\n- Nuclear fusion (potentially limitless clean energy)';

const c18 = 'CIRCULAR ECONOMY\n\nThe circular economy is an alternative to the linear "take-make-dispose" model. It keeps resources in use for as long as possible.\n\nLINEAR vs CIRCULAR:\nLinear: Extract -> Make -> Use -> Dispose\nCircular: Design -> Make -> Use -> Recover -> Regenerate\n\nTHREE PRINCIPLES:\n1. Design out waste and pollution\n2. Keep products and materials in use\n3. Regenerate natural systems\n\nCIRCULAR STRATEGIES:\n- Refuse: Avoid unnecessary products\n- Reduce: Use less material\n- Reuse: Use products multiple times\n- Repair: Fix broken products\n- Remanufacture: Rebuild to original quality\n- Recycle: Process into new materials\n\nBUSINESS MODELS:\n1. Product-as-a-Service - lease instead of sell\n2. Industrial Symbiosis - one company waste is another resource\n3. Sharing Economy - maximize utilization\n4. Repair and Remanufacturing\n\nECONOMIC OPPORTUNITY:\n- Could generate $4.5 trillion by 2030\n- Create 700,000 new jobs in Europe alone\n- Reduce CO2 emissions by 48% by 2030\n\nPOLICY EXAMPLES:\n- EU Circular Economy Action Plan\n- Right to Repair legislation\n- Extended Producer Responsibility';

const c19 = 'SOIL HEALTH AND AGRICULTURE\n\nHealthy soil is the foundation of all food production. A single teaspoon contains more microorganisms than there are people on Earth.\n\nSOIL FACTS:\n- Soil stores more carbon than all plants and the atmosphere combined\n- 95% of our food comes from soil\n- Takes 500-1000 years to form just 2.5cm of topsoil\n- We are losing 24 billion tonnes of fertile soil every year\n\nTHREATS TO SOIL:\n1. Chemical fertilizers and pesticides kill soil organisms\n2. Monoculture farming depletes nutrients\n3. Overgrazing compacts soil\n4. Erosion from deforestation\n5. Urbanization seals soil under concrete\n\nSUSTAINABLE PRACTICES:\n1. Composting - adds organic matter and nutrients\n2. Crop rotation - prevents nutrient depletion\n3. Cover cropping - protects soil between main crops\n4. Reduced tillage - preserves soil structure\n5. Agroforestry - integrates trees with crops\n6. Organic farming - avoids synthetic chemicals\n\nREGENERATIVE AGRICULTURE:\nGoes beyond sustainable to actively restore soil health and sequester carbon:\n- No-till or minimal tillage\n- Diverse crop rotations\n- Integrating livestock\n- Maintaining living roots year-round\n\nWHY IT MATTERS FOR CLIMATE:\nHealthy soils can sequester 1.85 billion tonnes of carbon per year.';

const lessons = [
  { title: 'What is Climate Change?', topic: 'Climate', type: 'text', difficulty: 'beginner', world: 'forest', points: 10, content: c1 },
  { title: 'Biodiversity and Ecosystems', topic: 'Biodiversity', type: 'text', difficulty: 'advanced', world: 'forest', points: 30, content: c2 },
  { title: 'Deforestation and Its Impact', topic: 'Forests', type: 'text', difficulty: 'intermediate', world: 'forest', points: 20, content: c3 },
  { title: 'Carbon Footprint Basics', topic: 'Climate', type: 'text', difficulty: 'beginner', world: 'forest', points: 10, content: c4 },
  { title: 'Ocean Pollution and You', topic: 'Ocean', type: 'text', difficulty: 'beginner', world: 'ocean', points: 10, content: c5 },
  { title: 'Ocean Acidification', topic: 'Ocean', type: 'text', difficulty: 'intermediate', world: 'ocean', points: 20, content: c6 },
  { title: 'Renewable Energy Sources', topic: 'Energy', type: 'text', difficulty: 'intermediate', world: 'city', points: 20, content: c7 },
  { title: 'Waste Segregation Basics', topic: 'Waste', type: 'game', difficulty: 'beginner', world: 'city', points: 15, content: c8 },
  { title: 'Sustainable Cities', topic: 'Urban', type: 'text', difficulty: 'intermediate', world: 'city', points: 20, content: c9 },
  { title: 'Water Conservation', topic: 'Water', type: 'text', difficulty: 'beginner', world: 'city', points: 10, content: c10 },
  { title: 'Air Quality and Health', topic: 'Pollution', type: 'text', difficulty: 'intermediate', world: 'city', points: 20, content: c11 },
  { title: 'Food Systems and Sustainability', topic: 'Food', type: 'text', difficulty: 'intermediate', world: 'forest', points: 20, content: c12 },
  { title: 'Climate Justice', topic: 'Climate', type: 'text', difficulty: 'advanced', world: 'forest', points: 30, content: c13 },
  { title: 'Marine Ecosystems', topic: 'Marine Life', type: 'text', difficulty: 'beginner', world: 'ocean', points: 10, content: c14 },
  { title: 'Sustainable Fishing', topic: 'Ocean', type: 'text', difficulty: 'intermediate', world: 'ocean', points: 20, content: c15 },
  { title: 'Plastic Pollution Crisis', topic: 'Waste', type: 'text', difficulty: 'beginner', world: 'ocean', points: 10, content: c16 },
  { title: 'Green Technology and Innovation', topic: 'Technology', type: 'text', difficulty: 'advanced', world: 'city', points: 30, content: c17 },
  { title: 'Circular Economy', topic: 'Economy', type: 'text', difficulty: 'advanced', world: 'city', points: 30, content: c18 },
  { title: 'Soil Health and Agriculture', topic: 'Agriculture', type: 'text', difficulty: 'intermediate', world: 'forest', points: 20, content: c19 },
];

const quizzes = [
  { title: 'Climate Change Fundamentals', points: 25, lessonIndex: 0, questions: [
    { question: 'What is the primary cause of modern climate change?', options: ['Volcanic eruptions', 'Human activities burning fossil fuels', 'Solar flares', 'Natural ocean cycles'], correctAnswer: 1, explanation: 'Human activities, especially burning coal, oil and gas, are the primary driver of modern climate change.' },
    { question: 'By how much has Earth warmed since pre-industrial times?', options: ['0.5 degrees C', '1.2 degrees C', '2.5 degrees C', '3.0 degrees C'], correctAnswer: 1, explanation: 'Earth has warmed approximately 1.2 degrees C since the pre-industrial era.' },
    { question: 'What does the Paris Agreement aim to limit warming to?', options: ['1.0 degrees C', '1.5 degrees C', '2.0 degrees C', '2.5 degrees C'], correctAnswer: 1, explanation: 'The Paris Agreement aims to limit global warming to 1.5 degrees C above pre-industrial levels.' },
    { question: 'Which gas is the main greenhouse gas from human activities?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctAnswer: 2, explanation: 'CO2 from burning fossil fuels is the primary greenhouse gas driving climate change.' },
    { question: 'What percentage of global emissions does the energy sector produce?', options: ['14%', '24%', '34%', '44%'], correctAnswer: 2, explanation: 'Energy production accounts for approximately 34% of global greenhouse gas emissions.' },
  ]},
  { title: 'Biodiversity Assessment', points: 30, lessonIndex: 1, questions: [
    { question: 'What percentage of terrestrial species live in forests?', options: ['40%', '60%', '80%', '95%'], correctAnswer: 2, explanation: 'Forests are home to approximately 80% of all terrestrial species.' },
    { question: 'How many species currently face extinction?', options: ['100,000', '500,000', '1 million', '5 million'], correctAnswer: 2, explanation: 'According to IPBES, approximately 1 million species currently face extinction.' },
    { question: 'Which is NOT a threat to biodiversity?', options: ['Habitat destruction', 'Climate change', 'Photosynthesis', 'Invasive species'], correctAnswer: 2, explanation: 'Photosynthesis is a natural process that supports life, not a threat to biodiversity.' },
    { question: 'What percentage of cancer drugs come from nature?', options: ['30%', '50%', '70%', '90%'], correctAnswer: 2, explanation: 'Approximately 70% of cancer drugs are derived from natural sources.' },
    { question: 'What is the current extinction event called?', options: ['5th mass extinction', '6th mass extinction', 'Holocene extinction', 'Both B and C'], correctAnswer: 3, explanation: 'The current event is called both the 6th mass extinction and the Holocene extinction.' },
  ]},
  { title: 'Deforestation Quiz', points: 25, lessonIndex: 2, questions: [
    { question: 'How many hectares of forest are lost every year?', options: ['1 million', '5 million', '10 million', '20 million'], correctAnswer: 2, explanation: 'Approximately 10 million hectares of forest are lost every year.' },
    { question: 'What is the main cause of deforestation?', options: ['Logging', 'Agriculture', 'Mining', 'Urbanization'], correctAnswer: 1, explanation: 'Agriculture accounts for approximately 80% of deforestation, mainly cattle ranching and soy production.' },
    { question: 'What percentage of global CO2 emissions does deforestation cause?', options: ['2%', '5%', '10%', '20%'], correctAnswer: 2, explanation: 'Deforestation is responsible for approximately 10% of global CO2 emissions.' },
    { question: 'What percentage of terrestrial species live in forests?', options: ['40%', '60%', '80%', '95%'], correctAnswer: 2, explanation: 'Approximately 80% of all terrestrial species live in forests.' },
    { question: 'How much of the Amazon has been lost in 50 years?', options: ['5%', '10%', '17%', '30%'], correctAnswer: 2, explanation: 'The Amazon has lost approximately 17% of its forest cover in the last 50 years.' },
  ]},
  { title: 'Carbon Footprint Challenge', points: 25, lessonIndex: 3, questions: [
    { question: 'What is the average carbon footprint per person in the USA?', options: ['4 tonnes', '8 tonnes', '16 tonnes', '24 tonnes'], correctAnswer: 2, explanation: 'The average American has a carbon footprint of approximately 16 tonnes CO2e per year.' },
    { question: 'Which food has the highest carbon footprint per kg?', options: ['Chicken', 'Pork', 'Beef', 'Lamb'], correctAnswer: 2, explanation: 'Beef produces approximately 60kg CO2e per kg - the highest of any common food.' },
    { question: 'What is the global target carbon footprint per person by 2050?', options: ['Under 2 tonnes', 'Under 5 tonnes', 'Under 8 tonnes', 'Under 10 tonnes'], correctAnswer: 0, explanation: 'To limit warming to 1.5 degrees C, the global average needs to fall to under 2 tonnes per person by 2050.' },
    { question: 'Which transport mode has the highest carbon footprint per km?', options: ['Car', 'Train', 'Short-haul flight', 'Long-haul flight'], correctAnswer: 2, explanation: 'Short-haul flights have the highest carbon footprint per km due to fuel use during takeoff and landing.' },
    { question: 'What percentage of global emissions does the food system produce?', options: ['10%', '18%', '26%', '35%'], correctAnswer: 2, explanation: 'The global food system accounts for approximately 26% of greenhouse gas emissions.' },
  ]},
  { title: 'Ocean Pollution Quiz', points: 25, lessonIndex: 4, questions: [
    { question: 'How much plastic enters the ocean every year?', options: ['1 million tonnes', '4 million tonnes', '8 million tonnes', '20 million tonnes'], correctAnswer: 2, explanation: 'Approximately 8 million tonnes of plastic enter the oceans every year.' },
    { question: 'What percentage of coral reefs have been lost since 1950?', options: ['20%', '35%', '50%', '70%'], correctAnswer: 2, explanation: 'About 50% of the world coral reefs have been lost since 1950.' },
    { question: 'What percentage of Earth oxygen does the ocean produce?', options: ['20%', '35%', '50%', '70%'], correctAnswer: 2, explanation: 'Marine phytoplankton produce approximately 50% of Earth oxygen.' },
    { question: 'How much of human CO2 emissions has the ocean absorbed?', options: ['10%', '20%', '30%', '40%'], correctAnswer: 2, explanation: 'The ocean has absorbed approximately 30% of all human CO2 emissions.' },
    { question: 'What is the Great Pacific Garbage Patch?', options: ['A recycling facility', 'A concentration of marine debris', 'An oil spill', 'A coral reef'], correctAnswer: 1, explanation: 'The Great Pacific Garbage Patch is a massive concentration of marine debris, mostly microplastics.' },
  ]},
  { title: 'Ocean Acidification Test', points: 25, lessonIndex: 5, questions: [
    { question: 'What causes ocean acidification?', options: ['Plastic pollution', 'CO2 dissolving in seawater', 'Oil spills', 'Overfishing'], correctAnswer: 1, explanation: 'Ocean acidification is caused by CO2 from the atmosphere dissolving in seawater, forming carbonic acid.' },
    { question: 'By how much has ocean acidity increased since industrialisation?', options: ['10%', '26%', '50%', '75%'], correctAnswer: 1, explanation: 'Ocean acidity has increased by approximately 26% since industrialisation.' },
    { question: 'Which organisms are most immediately threatened by acidification?', options: ['Whales', 'Sharks', 'Shellfish and corals', 'Dolphins'], correctAnswer: 2, explanation: 'Shellfish and corals are most immediately threatened because they need alkaline water to form their shells.' },
    { question: 'What is the only long-term solution to ocean acidification?', options: ['Adding limestone to oceans', 'Reducing CO2 emissions', 'Banning fishing', 'Building sea walls'], correctAnswer: 1, explanation: 'Reducing CO2 emissions is the only long-term solution to ocean acidification.' },
    { question: 'What percentage of CO2 emissions has the ocean absorbed?', options: ['10%', '20%', '30%', '40%'], correctAnswer: 2, explanation: 'The ocean has absorbed approximately 30% of all human CO2 emissions since industrialisation.' },
  ]},
  { title: 'Renewable Energy Assessment', points: 30, lessonIndex: 6, questions: [
    { question: 'By how much have solar panel costs dropped in 10 years?', options: ['30%', '60%', '90%', '95%'], correctAnswer: 2, explanation: 'Solar panel costs have dropped by approximately 90% over the past decade.' },
    { question: 'What percentage of global electricity do renewables supply?', options: ['10%', '20%', '30%', '50%'], correctAnswer: 2, explanation: 'Renewables now supply approximately 30% of global electricity generation.' },
    { question: 'Which renewable energy source is currently the largest globally?', options: ['Solar', 'Wind', 'Hydropower', 'Geothermal'], correctAnswer: 2, explanation: 'Hydropower remains the largest source of renewable electricity globally.' },
    { question: 'What is the main challenge for 24/7 renewable energy?', options: ['Cost', 'Energy storage', 'Land use', 'Public acceptance'], correctAnswer: 1, explanation: 'Energy storage (batteries) is the main challenge for continuous renewable energy supply.' },
    { question: 'Which country generates the most solar energy?', options: ['USA', 'Germany', 'China', 'India'], correctAnswer: 2, explanation: 'China is the world largest producer of solar energy, accounting for about 35% of global capacity.' },
  ]},
  { title: 'Waste and Recycling Test', points: 20, lessonIndex: 7, questions: [
    { question: 'What percentage of all plastic ever produced has been recycled?', options: ['9%', '25%', '40%', '60%'], correctAnswer: 0, explanation: 'Only 9% of all plastic ever produced has been recycled.' },
    { question: 'Which waste category does food scraps belong to?', options: ['Recyclable', 'Compostable', 'General waste', 'Hazardous'], correctAnswer: 1, explanation: 'Food scraps are compostable - they can be turned into nutrient-rich compost.' },
    { question: 'What gas do landfills produce that contributes to climate change?', options: ['Carbon dioxide', 'Methane', 'Nitrous oxide', 'Ozone'], correctAnswer: 1, explanation: 'Landfills produce methane as organic waste decomposes. Methane is 80x more potent than CO2 over 20 years.' },
    { question: 'What is the correct waste hierarchy order?', options: ['Reduce, Reuse, Recycle', 'Refuse, Reduce, Reuse, Recycle, Rot', 'Recycle, Reduce, Reuse', 'Reuse, Recycle, Reduce'], correctAnswer: 1, explanation: 'The full waste hierarchy is: Refuse, Reduce, Reuse, Recycle, Rot (compost).' },
    { question: 'How long does a plastic bottle take to decompose?', options: ['10 years', '50 years', '200 years', '400-1000 years'], correctAnswer: 3, explanation: 'Plastic bottles take 400-1000 years to decompose.' },
  ]},
  { title: 'Sustainable Cities Assessment', points: 25, lessonIndex: 8, questions: [
    { question: 'What percentage of global resources do cities consume?', options: ['25%', '50%', '75%', '90%'], correctAnswer: 2, explanation: 'Cities cover only 3% of land but consume approximately 75% of global resources.' },
    { question: 'By how much does public transport reduce per-person emissions?', options: ['15%', '30%', '45%', '60%'], correctAnswer: 2, explanation: 'Using public transport instead of a private car can reduce per-person emissions by approximately 45%.' },
    { question: 'What percentage of Copenhagen residents cycle to work?', options: ['22%', '42%', '62%', '82%'], correctAnswer: 2, explanation: 'Approximately 62% of Copenhagen residents cycle to work.' },
    { question: 'What is a green roof?', options: ['A roof painted green', 'A roof covered with vegetation', 'A solar panel roof', 'An energy-efficient roof'], correctAnswer: 1, explanation: 'A green roof is covered with vegetation and soil, providing insulation and supporting biodiversity.' },
    { question: 'What percentage of greenhouse gases do cities produce?', options: ['40%', '60%', '80%', '95%'], correctAnswer: 2, explanation: 'Cities produce approximately 80% of global greenhouse gas emissions.' },
  ]},
  { title: 'Water Conservation Quiz', points: 20, lessonIndex: 9, questions: [
    { question: 'What percentage of Earth water is fresh?', options: ['1%', '3%', '10%', '25%'], correctAnswer: 1, explanation: 'Only 3% of Earth water is fresh, and less than 1% is accessible for human use.' },
    { question: 'How much water does agriculture use globally?', options: ['30%', '50%', '70%', '90%'], correctAnswer: 2, explanation: 'Agriculture accounts for approximately 70% of global freshwater withdrawals.' },
    { question: 'How many litres of water does producing 1kg of beef require?', options: ['1,000', '5,000', '10,000', '15,000'], correctAnswer: 3, explanation: 'Producing 1kg of beef requires approximately 15,000 litres of water.' },
    { question: 'How much water does a dripping tap waste per year?', options: ['100 gallons', '500 gallons', '3,000 gallons', '10,000 gallons'], correctAnswer: 2, explanation: 'A dripping tap can waste approximately 3,000 gallons of water per year.' },
    { question: 'By 2025, what fraction of the world may face water scarcity?', options: ['One quarter', 'One third', 'Half', 'Two thirds'], correctAnswer: 2, explanation: 'By 2025, approximately half the world population could face high water stress.' },
  ]},
  { title: 'Air Quality Quiz', points: 20, lessonIndex: 10, questions: [
    { question: 'How many people does air pollution kill per year?', options: ['1 million', '3 million', '7 million', '10 million'], correctAnswer: 2, explanation: 'Air pollution kills approximately 7 million people per year worldwide.' },
    { question: 'Which pollutant is most dangerous to human health?', options: ['NO2', 'PM2.5', 'Ozone', 'SO2'], correctAnswer: 1, explanation: 'PM2.5 (fine particles) is most dangerous as it penetrates deep into lungs and enters the bloodstream.' },
    { question: 'What percentage of the world population breathes air exceeding WHO guidelines?', options: ['50%', '75%', '90%', '99%'], correctAnswer: 3, explanation: '99% of the world population breathes air that exceeds WHO air quality guidelines.' },
    { question: 'What is the main source of NO2 pollution in cities?', options: ['Factories', 'Vehicles', 'Agriculture', 'Cooking'], correctAnswer: 1, explanation: 'Vehicles are the main source of NO2 pollution in urban areas.' },
    { question: 'Which group is most vulnerable to air pollution?', options: ['Adults', 'Athletes', 'Children', 'Teenagers'], correctAnswer: 2, explanation: 'Children are most vulnerable because their lungs are still developing.' },
  ]},
  { title: 'Food Sustainability Test', points: 25, lessonIndex: 11, questions: [
    { question: 'What percentage of greenhouse gas emissions does the food system produce?', options: ['10%', '18%', '26%', '35%'], correctAnswer: 2, explanation: 'The global food system accounts for approximately 26% of greenhouse gas emissions.' },
    { question: 'What fraction of all food produced is wasted?', options: ['1/10', '1/5', '1/3', '1/2'], correctAnswer: 2, explanation: 'Approximately 1/3 of all food produced globally is wasted.' },
    { question: 'How much less land does a vegan diet use compared to average?', options: ['25% less', '50% less', '75% less', '90% less'], correctAnswer: 2, explanation: 'A vegan diet uses approximately 75% less land than an average diet.' },
    { question: 'Which food has the highest carbon footprint per kg?', options: ['Chicken', 'Pork', 'Beef', 'Cheese'], correctAnswer: 2, explanation: 'Beef has the highest carbon footprint at approximately 60kg CO2e per kg.' },
    { question: 'What percentage of freshwater does agriculture use?', options: ['30%', '50%', '70%', '90%'], correctAnswer: 2, explanation: 'Agriculture accounts for approximately 70% of global freshwater withdrawals.' },
  ]},
  { title: 'Climate Justice Quiz', points: 30, lessonIndex: 12, questions: [
    { question: 'What percentage of emissions are the richest 10% responsible for?', options: ['20%', '35%', '50%', '65%'], correctAnswer: 2, explanation: 'The richest 10% of the world population is responsible for approximately 50% of global emissions.' },
    { question: 'Which region faces the worst climate impacts despite contributing least?', options: ['North America', 'Europe', 'Sub-Saharan Africa', 'East Asia'], correctAnswer: 2, explanation: 'Sub-Saharan Africa faces severe climate impacts including droughts and crop failures, despite contributing very little to global emissions.' },
    { question: 'How many people could be displaced by 1m sea level rise in Bangladesh?', options: ['1 million', '5 million', '17 million', '50 million'], correctAnswer: 2, explanation: 'A 1-metre sea level rise could displace approximately 17 million people in Bangladesh.' },
    { question: 'What is "loss and damage" in climate negotiations?', options: ['Insurance for climate disasters', 'Compensation for unavoidable climate impacts', 'Carbon credits', 'Emission reduction targets'], correctAnswer: 1, explanation: 'Loss and damage refers to compensation for climate impacts that cannot be adapted to.' },
    { question: 'What does climate justice demand from wealthy nations?', options: ['Build more coal plants', 'Cut emissions fastest and provide climate finance', 'Ignore developing nations', 'Focus only on adaptation'], correctAnswer: 1, explanation: 'Climate justice demands that wealthy nations cut emissions fastest and provide finance to help developing nations adapt.' },
  ]},
  { title: 'Marine Ecosystems Quiz', points: 20, lessonIndex: 13, questions: [
    { question: 'What percentage of marine species live in coral reefs?', options: ['5%', '15%', '25%', '40%'], correctAnswer: 2, explanation: 'Coral reefs cover less than 1% of the ocean floor but are home to 25% of all marine species.' },
    { question: 'What do mangroves provide for fish?', options: ['Food only', 'Nursery habitat', 'Oxygen', 'Shelter from predators only'], correctAnswer: 1, explanation: 'Mangroves serve as nurseries for approximately 75% of tropical fish species.' },
    { question: 'What percentage of Earth oxygen do marine phytoplankton produce?', options: ['20%', '35%', '50%', '70%'], correctAnswer: 2, explanation: 'Marine phytoplankton produce approximately 50% of Earth oxygen through photosynthesis.' },
    { question: 'Which marine ecosystem stores the most carbon per hectare?', options: ['Coral reefs', 'Open ocean', 'Seagrass meadows', 'Mangroves'], correctAnswer: 3, explanation: 'Mangroves store 3-5x more carbon per hectare than tropical forests.' },
    { question: 'What is the main threat to deep sea ecosystems?', options: ['Overfishing', 'Plastic pollution', 'Deep-sea mining', 'Climate change'], correctAnswer: 2, explanation: 'Deep-sea mining is the main emerging threat to deep sea ecosystems.' },
  ]},
  { title: 'Sustainable Fishing Test', points: 20, lessonIndex: 14, questions: [
    { question: 'What percentage of fish stocks are fully exploited or overfished?', options: ['50%', '70%', '90%', '95%'], correctAnswer: 2, explanation: 'Approximately 90% of the world fish stocks are fully exploited or overfished.' },
    { question: 'What is bycatch?', options: ['Catching fish illegally', 'Unintended species caught during fishing', 'Farmed fish', 'Fish caught at night'], correctAnswer: 1, explanation: 'Bycatch refers to unintended species caught during fishing operations - about 40% of all catch.' },
    { question: 'What does MSC certification indicate?', options: ['Marine Safety Compliance', 'Marine Stewardship Council - sustainable fishing', 'Maximum Sustainable Catch', 'Marine Species Conservation'], correctAnswer: 1, explanation: 'MSC (Marine Stewardship Council) certification indicates that fish was caught using sustainable methods.' },
    { question: 'What percentage of the ocean do Marine Protected Areas currently cover?', options: ['2%', '5%', '8%', '15%'], correctAnswer: 2, explanation: 'Marine Protected Areas currently cover approximately 8% of the ocean.' },
    { question: 'What is the 30x30 initiative?', options: ['Catch 30% more fish by 2030', 'Protect 30% of ocean by 2030', 'Reduce fishing by 30% by 2030', 'Create 30 new MPAs by 2030'], correctAnswer: 1, explanation: 'The 30x30 initiative aims to protect 30% of the ocean by 2030.' },
  ]},
  { title: 'Plastic Pollution Quiz', points: 20, lessonIndex: 15, questions: [
    { question: 'What percentage of all plastic ever produced has been recycled?', options: ['9%', '25%', '40%', '60%'], correctAnswer: 0, explanation: 'Only 9% of all plastic ever produced has been recycled.' },
    { question: 'How long does a plastic bottle take to decompose?', options: ['10 years', '50 years', '200 years', '400-1000 years'], correctAnswer: 3, explanation: 'Plastic bottles take 400-1000 years to decompose.' },
    { question: 'How much microplastic does the average person consume per week?', options: ['1g', '5g', '10g', '20g'], correctAnswer: 1, explanation: 'Humans consume about 5g of microplastics per week - equivalent to a credit card.' },
    { question: 'What is the Great Pacific Garbage Patch?', options: ['A recycling facility', 'A concentration of marine debris', 'An oil spill', 'A coral reef'], correctAnswer: 1, explanation: 'The Great Pacific Garbage Patch is a massive concentration of marine debris, mostly microplastics.' },
    { question: 'What is the first step in the plastic solution hierarchy?', options: ['Recycle', 'Reduce', 'Reuse', 'Refuse'], correctAnswer: 3, explanation: 'Refuse is the first and most effective step - do not accept single-use plastics in the first place.' },
  ]},
  { title: 'Green Technology Quiz', points: 30, lessonIndex: 16, questions: [
    { question: 'By how much have battery costs for EVs dropped since 1991?', options: ['50%', '75%', '90%', '97%'], correctAnswer: 3, explanation: 'Battery costs for electric vehicles have dropped by approximately 97% since 1991.' },
    { question: 'What is green hydrogen?', options: ['Hydrogen from natural gas', 'Hydrogen produced using renewable energy', 'Hydrogen from coal', 'Hydrogen from nuclear power'], correctAnswer: 1, explanation: 'Green hydrogen is produced by electrolysis using renewable energy, resulting in zero emissions.' },
    { question: 'How much less water does vertical farming use?', options: ['50% less', '75% less', '90% less', '95% less'], correctAnswer: 3, explanation: 'Vertical farming uses approximately 95% less water than conventional farming.' },
    { question: 'What does CCS stand for?', options: ['Clean Carbon System', 'Carbon Capture and Storage', 'Climate Change Solutions', 'Carbon Credit Scheme'], correctAnswer: 1, explanation: 'CCS stands for Carbon Capture and Storage - technology that captures CO2 from industrial processes.' },
    { question: 'By how much can smart building systems reduce energy use?', options: ['10%', '20%', '30%', '50%'], correctAnswer: 2, explanation: 'Smart building management systems can reduce building energy use by approximately 30%.' },
  ]},
  { title: 'Circular Economy Test', points: 30, lessonIndex: 17, questions: [
    { question: 'What is the circular economy alternative to?', options: ['Renewable energy', 'Linear take-make-dispose model', 'Recycling only', 'Sustainable agriculture'], correctAnswer: 1, explanation: 'The circular economy is an alternative to the linear "take-make-dispose" model.' },
    { question: 'How much could the circular economy generate by 2030?', options: ['$1 trillion', '$2.5 trillion', '$4.5 trillion', '$10 trillion'], correctAnswer: 2, explanation: 'The circular economy could generate approximately $4.5 trillion in economic value by 2030.' },
    { question: 'What is "product-as-a-service"?', options: ['Selling products online', 'Leasing products instead of selling them', 'Repairing products', 'Recycling products'], correctAnswer: 1, explanation: 'Product-as-a-service means leasing products instead of selling them, keeping the manufacturer responsible for end-of-life.' },
    { question: 'What is industrial symbiosis?', options: ['Two companies competing', 'One company waste becomes another resource', 'Sharing factory space', 'Joint marketing'], correctAnswer: 1, explanation: 'Industrial symbiosis is when one company waste or byproduct becomes a resource for another company.' },
    { question: 'By how much could the circular economy reduce CO2 emissions by 2030?', options: ['20%', '35%', '48%', '60%'], correctAnswer: 2, explanation: 'The circular economy could reduce CO2 emissions by approximately 48% by 2030.' },
  ]},
  { title: 'Soil Health Quiz', points: 20, lessonIndex: 18, questions: [
    { question: 'How long does it take to form 2.5cm of topsoil naturally?', options: ['10-50 years', '100-200 years', '500-1000 years', '2000-5000 years'], correctAnswer: 2, explanation: 'It takes approximately 500-1000 years to form just 2.5cm of topsoil naturally.' },
    { question: 'What percentage of our food comes from soil?', options: ['60%', '75%', '85%', '95%'], correctAnswer: 3, explanation: 'Approximately 95% of our food comes from soil.' },
    { question: 'How many tonnes of fertile soil are we losing every year?', options: ['1 billion', '5 billion', '12 billion', '24 billion'], correctAnswer: 3, explanation: 'We are losing approximately 24 billion tonnes of fertile soil every year.' },
    { question: 'What is regenerative agriculture?', options: ['Farming with chemicals', 'Farming that restores soil health and sequesters carbon', 'Organic farming only', 'Vertical farming'], correctAnswer: 1, explanation: 'Regenerative agriculture goes beyond sustainable to actively restore soil health and sequester carbon.' },
    { question: 'How much carbon can healthy soils sequester per year?', options: ['500 million tonnes', '1 billion tonnes', '1.85 billion tonnes', '5 billion tonnes'], correctAnswer: 2, explanation: 'Healthy soils can sequester approximately 1.85 billion tonnes of carbon per year.' },
  ]},
  { title: 'Comprehensive Eco Assessment', points: 40, lessonIndex: 0, questions: [
    { question: 'Which sector produces the most greenhouse gas emissions globally?', options: ['Transport', 'Agriculture', 'Energy production', 'Industry'], correctAnswer: 2, explanation: 'Energy production (electricity and heat) accounts for approximately 34% of global greenhouse gas emissions.' },
    { question: 'What is the most effective personal action to reduce carbon footprint?', options: ['Recycling more', 'Eating less meat', 'Turning off lights', 'Using reusable bags'], correctAnswer: 1, explanation: 'Eating less meat, especially beef, is the most impactful personal action for reducing carbon footprint.' },
    { question: 'Which ecosystem stores the most carbon per hectare?', options: ['Tropical rainforest', 'Temperate forest', 'Mangroves', 'Grassland'], correctAnswer: 2, explanation: 'Mangroves store 3-5x more carbon per hectare than tropical forests.' },
    { question: 'What percentage of the world population lacks access to safe drinking water?', options: ['5%', '15%', '25%', '35%'], correctAnswer: 2, explanation: 'Approximately 2 billion people (25% of world population) lack access to safe drinking water.' },
    { question: 'Which country has the highest per-capita carbon footprint?', options: ['China', 'USA', 'Australia', 'Saudi Arabia'], correctAnswer: 1, explanation: 'The USA has one of the highest per-capita carbon footprints at approximately 16 tonnes CO2e per year.' },
    { question: 'What is the target for protected ocean area by 2030?', options: ['10%', '20%', '30%', '50%'], correctAnswer: 2, explanation: 'The 30x30 initiative aims to protect 30% of the ocean by 2030.' },
    { question: 'How much of global electricity do renewables currently supply?', options: ['10%', '20%', '30%', '50%'], correctAnswer: 2, explanation: 'Renewables now supply approximately 30% of global electricity generation.' },
    { question: 'What is the main driver of biodiversity loss?', options: ['Climate change', 'Pollution', 'Land use change', 'Invasive species'], correctAnswer: 2, explanation: 'Land use change (habitat destruction for agriculture and development) is the main driver of biodiversity loss.' },
  ]},
];

const challenges = [
  { taskName: 'Plant a Tree', description: 'Plant a tree in your garden, school, or community space. Submit a photo with the sapling.', proofType: 'photo', points: 100, world: 'forest' },
  { taskName: 'Zero Waste Day', description: 'Spend an entire day producing zero waste. Document everything you refused, reduced, or composted.', proofType: 'text', points: 75, world: 'city' },
  { taskName: 'Beach or Park Cleanup', description: 'Organise or join a cleanup of a beach, park, or river. Submit photos of the waste collected.', proofType: 'both', points: 150, world: 'ocean' },
  { taskName: 'Switch to Reusables', description: 'Replace 5 single-use items with reusable alternatives this week. List what you switched.', proofType: 'text', points: 50, world: 'city' },
  { taskName: 'Meatless Week', description: 'Go meat-free for an entire week. Share your meals and how you felt about the experience.', proofType: 'text', points: 80, world: 'forest' },
  { taskName: 'Cycle or Walk to School', description: 'Cycle or walk to school or work for 5 consecutive days instead of using a car or bus.', proofType: 'text', points: 60, world: 'city' },
  { taskName: 'Start a Compost Bin', description: 'Set up a compost bin at home or school. Document the setup and first week of composting.', proofType: 'both', points: 90, world: 'forest' },
  { taskName: 'Energy Audit', description: 'Conduct an energy audit of your home or classroom. Identify 5 ways to reduce energy use.', proofType: 'text', points: 70, world: 'city' },
  { taskName: 'Teach Someone About Climate', description: 'Teach a family member or friend about one climate change topic. Describe what you taught and their reaction.', proofType: 'text', points: 40, world: 'forest' },
  { taskName: 'Ocean Awareness Campaign', description: 'Create a poster, social media post, or presentation about ocean pollution. Share it with at least 10 people.', proofType: 'both', points: 120, world: 'ocean' },
  { taskName: 'Grow Your Own Food', description: 'Grow at least one vegetable, herb, or fruit from seed. Document the growth over 2 weeks.', proofType: 'photo', points: 85, world: 'forest' },
  { taskName: 'Reduce Screen Time Energy', description: 'Reduce your device screen time by 30% for one week to save electricity. Track your usage.', proofType: 'text', points: 45, world: 'city' },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  await Lesson.deleteMany();
  await Quiz.deleteMany();
  await Challenge.deleteMany();

  const createdLessons = await Lesson.insertMany(lessons);
  console.log(createdLessons.length + ' lessons seeded');

  const quizDocs = quizzes.map(function(q) {
    return {
      lessonId: createdLessons[q.lessonIndex] ? createdLessons[q.lessonIndex]._id : createdLessons[0]._id,
      title: q.title,
      points: q.points,
      questions: q.questions,
    };
  });
  await Quiz.insertMany(quizDocs);
  console.log(quizDocs.length + ' quizzes seeded');

  await Challenge.insertMany(challenges);
  console.log(challenges.length + ' challenges seeded');

  const existing = await User.findOne({ email: 'admin@ecoverse.com' });
  if (!existing) {
    await User.create({ name: 'Admin', email: 'admin@ecoverse.com', password: 'admin123', role: 'admin' });
    console.log('Admin created: admin@ecoverse.com / admin123');
  }

  console.log('Seed complete!');
  process.exit(0);
}

seed().catch(function(err) { console.error(err); process.exit(1); });
